/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ComplianceScoreRouteImport } from './routes/compliance-score'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsThreatIntelligenceRouteImport } from './routes/solutions.threat-intelligence'
import { Route as SolutionsInfrastructureVisibilityRouteImport } from './routes/solutions.infrastructure-visibility'
import { Route as SolutionsDpdpComplianceRouteImport } from './routes/solutions.dpdp-compliance'
import { Route as SolutionsAiCopilotRouteImport } from './routes/solutions.ai-copilot'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceScoreRoute = ComplianceScoreRouteImport.update({
  id: '/compliance-score',
  path: '/compliance-score',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsThreatIntelligenceRoute =
  SolutionsThreatIntelligenceRouteImport.update({
    id: '/solutions/threat-intelligence',
    path: '/solutions/threat-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsInfrastructureVisibilityRoute =
  SolutionsInfrastructureVisibilityRouteImport.update({
    id: '/solutions/infrastructure-visibility',
    path: '/solutions/infrastructure-visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsDpdpComplianceRoute = SolutionsDpdpComplianceRouteImport.update({
  id: '/solutions/dpdp-compliance',
  path: '/solutions/dpdp-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAiCopilotRoute = SolutionsAiCopilotRouteImport.update({
  id: '/solutions/ai-copilot',
  path: '/solutions/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance-score': typeof ComplianceScoreRoute
  '/pricing': typeof PricingRoute
  '/solutions/ai-copilot': typeof SolutionsAiCopilotRoute
  '/solutions/dpdp-compliance': typeof SolutionsDpdpComplianceRoute
  '/solutions/infrastructure-visibility': typeof SolutionsInfrastructureVisibilityRoute
  '/solutions/threat-intelligence': typeof SolutionsThreatIntelligenceRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance-score': typeof ComplianceScoreRoute
  '/pricing': typeof PricingRoute
  '/solutions/ai-copilot': typeof SolutionsAiCopilotRoute
  '/solutions/dpdp-compliance': typeof SolutionsDpdpComplianceRoute
  '/solutions/infrastructure-visibility': typeof SolutionsInfrastructureVisibilityRoute
  '/solutions/threat-intelligence': typeof SolutionsThreatIntelligenceRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance-score': typeof ComplianceScoreRoute
  '/pricing': typeof PricingRoute
  '/solutions/ai-copilot': typeof SolutionsAiCopilotRoute
  '/solutions/dpdp-compliance': typeof SolutionsDpdpComplianceRoute
  '/solutions/infrastructure-visibility': typeof SolutionsInfrastructureVisibilityRoute
  '/solutions/threat-intelligence': typeof SolutionsThreatIntelligenceRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance-score'
    | '/pricing'
    | '/solutions/ai-copilot'
    | '/solutions/dpdp-compliance'
    | '/solutions/infrastructure-visibility'
    | '/solutions/threat-intelligence'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance-score'
    | '/pricing'
    | '/solutions/ai-copilot'
    | '/solutions/dpdp-compliance'
    | '/solutions/infrastructure-visibility'
    | '/solutions/threat-intelligence'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/compliance-score'
    | '/pricing'
    | '/solutions/ai-copilot'
    | '/solutions/dpdp-compliance'
    | '/solutions/infrastructure-visibility'
    | '/solutions/threat-intelligence'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceScoreRoute: typeof ComplianceScoreRoute
  PricingRoute: typeof PricingRoute
  SolutionsAiCopilotRoute: typeof SolutionsAiCopilotRoute
  SolutionsDpdpComplianceRoute: typeof SolutionsDpdpComplianceRoute
  SolutionsInfrastructureVisibilityRoute: typeof SolutionsInfrastructureVisibilityRoute
  SolutionsThreatIntelligenceRoute: typeof SolutionsThreatIntelligenceRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-score': {
      id: '/compliance-score'
      path: '/compliance-score'
      fullPath: '/compliance-score'
      preLoaderRoute: typeof ComplianceScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/threat-intelligence': {
      id: '/solutions/threat-intelligence'
      path: '/solutions/threat-intelligence'
      fullPath: '/solutions/threat-intelligence'
      preLoaderRoute: typeof SolutionsThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/infrastructure-visibility': {
      id: '/solutions/infrastructure-visibility'
      path: '/solutions/infrastructure-visibility'
      fullPath: '/solutions/infrastructure-visibility'
      preLoaderRoute: typeof SolutionsInfrastructureVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/dpdp-compliance': {
      id: '/solutions/dpdp-compliance'
      path: '/solutions/dpdp-compliance'
      fullPath: '/solutions/dpdp-compliance'
      preLoaderRoute: typeof SolutionsDpdpComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai-copilot': {
      id: '/solutions/ai-copilot'
      path: '/solutions/ai-copilot'
      fullPath: '/solutions/ai-copilot'
      preLoaderRoute: typeof SolutionsAiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceScoreRoute: ComplianceScoreRoute,
  PricingRoute: PricingRoute,
  SolutionsAiCopilotRoute: SolutionsAiCopilotRoute,
  SolutionsDpdpComplianceRoute: SolutionsDpdpComplianceRoute,
  SolutionsInfrastructureVisibilityRoute:
    SolutionsInfrastructureVisibilityRoute,
  SolutionsThreatIntelligenceRoute: SolutionsThreatIntelligenceRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
